name: Build & Test on Open PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '500'
      - name: build
        run: ./gradlew assembleDebug
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: test
        run: ./gradlew testDebug
